-- Apply only to the selected database after reviewing registration access policy.
CREATE TABLE IF NOT EXISTS voley_playa.usuario (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(40) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    CONSTRAINT vp_usuario_nombre CHECK (username ~ '^[a-z0-9][a-z0-9._-]{2,39}$')
);
